---
version: '2.0'
services:
  zabbix-test:
    image: zabbix-test
    environment:
      DB_SERVER_HOST:
      MYSQL_ROOT_PASSWORD:
  yamllint:
    image: boiyaa/yamllint:latest
    volumes:
      - ".:/workdir"
    working_dir: /workdir
  shush_decrypt:
    build:
     context: ./shush
     dockerfile: Dockerfile
    volumes:
      - "$HOME/.aws:/root/.aws"
    environment:
      AWS_DEFAULT_REGION: ap-southeast-2
