---
version: '2.0'
services:
  zabbix-semmer:
    image: zabbix-test
    environment:
      - DB_SERVER_HOST=localhost
      - MYSQL_ROOT_PASSWORD=password
  yamllint:
    image: boiyaa/yamllint:latest
    volumes:
      - ".:/workdir"
    working_dir: /workdir
  shush_decrypt:
    build:
     context: ./shush
     dockerfile: Dockerfile
